apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: dzhgauae1-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-7ee9d4cf2b.xkgu.p3.openshiftapps.com/rhtap/rhtap-qe:1c10351f70c686589ed0bd389a75fe7001ba7a0c@sha256:076f6ec6b2482ead152d3e860475e8beec2fac057672b9bf8e938a834169a20c
        name: container-image  
